
version: '3.4'

networks:
  serverapp:

services:
  db:
    container_name: authorverse-db
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - 1433:1433
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=S3cur3P@ssW0rd!
    networks:
        - serverapp

  redis:
    container_name: authorverse-redis
    image: redis
    ports:
        - 6379:6379 
    networks:
        - serverapp

  server:
    container_name: authorverse-server
    build:
      context: .
      target: final
    ports:
      - 7069:80
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=development
      - MSSQL_SA_PASSWORD=S3cur3P@ssW0rd!
    networks:
      - serverapp

